from sqlalchemy import (
    Column, Integer, BigInteger, String, Boolean, DateTime, Date, Enum, JSON, ForeignKey
)
from sqlalchemy.orm import declarative_base

Base = declarative_base()

class UserDetailsModel(Base):
    __tablename__ = 'users'

    id = Column(BigInteger, primary_key=True, autoincrement=True)
    email = Column(String(255), nullable=False)
    password_digest = Column(String(255))
    created_at = Column(DateTime, nullable=False)
    updated_at = Column(DateTime, nullable=False)
    email_verification_token = Column(String(255))
    verification_status = Column(Integer, nullable=False)
    first_name = Column(String(255))
    last_name = Column(String(255))
    google_secret = Column(String(255))
    seen_intro = Column(Boolean, default=False)
    enable_bots = Column(Boolean, default=False)
    last_seen = Column(DateTime)
    tracking_info = Column(JSON)
    country = Column(String(255))
    preferences = Column(JSON)
    phishing_code = Column(String(255))
    nick_name = Column(String(255))
    is_kyc_done = Column(Boolean, default=False)
    kyc_document_number = Column(String(255))
    password_updated_at = Column(DateTime)
    mfa_updated_at = Column(DateTime)
    kyc_level = Column(Integer, default=0)
    is_kyc_provisioned = Column(Boolean, default=False)
    parent_user_id = Column(Integer, ForeignKey('users.id'))
    country_calling_code = Column(Integer)
    phone_number = Column(BigInteger)
    phone_verification_status = Column(Integer, default=0)
    proof_of_identity_status = Column(String(255), default='pending', nullable=False)
    proof_of_address_status = Column(String(255), default='pending', nullable=False)
    dob = Column(Date)
    account_name = Column(String(255))
    is_login_enabled = Column(Boolean, default=True)
    is_withdrawal_enabled = Column(Boolean, default=True)
    is_kyc_refresh_required = Column(Boolean, default=False)
    kyc_expiry_date = Column(DateTime)
    margin_mode = Column(String(50), default="isolated")
    pf_index_symbol = Column(String(255), nullable=True)
    pf_index_symbols = Column(String(255), nullable=True)
    personal_kyc_details_verification_status = Column(Integer, default=1)
    permissions = Column(JSON, default={})
    oauth = Column(Integer, default=1)
    oauth_apple_active = Column(Boolean, default=False)
    oauth_google_active = Column(Boolean, default=True)
    is_deleted = Column(Boolean, default=False)
    sub_account_permissions = Column(JSON, nullable=True)
    region = Column(String(100), nullable=True)
    corporate_account_id = Column(String(255), nullable=True)
    occupation = Column(String(255), nullable=True)
    income = Column(String(255), nullable=True)
